### ISSUE TITLE
Does the "SignIn Audience" HAVE to be any directory + personal accounts?

### ISSUE THREAD

**Issue by inDDev** [microsoftgraph/msgraph-training-rubyrailsapp#12]
Thank you for this example. 

Would appreciate some help with an issue; In the instructions, it asks setting Supported account types to Accounts in any organisational directory and personal Microsoft accounts.

I have been able to successfully deploy on a test Azure account that has personal MS accounts in the directory, but I want to know if I can use this repo for an enterprise Azure account.

This is what I see in the Authentication Option under App Registrations: 

> Supported account types
> Who can use this application or access this API?
> (TICKED) Accounts in any organisational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)
> (ATTENTION ICON) All users with a work or school, or personal Microsoft account can use your application or API. This includes Office 365 subscribers.
> To change the supported accounts for an existing registration, use the manifest editor. Take care, as certain properties may cause errors for personal accounts.

And these are the options I see in the manifest documentation:

> AzureADMyOrg - Users with a Microsoft work or school account in my organization’s Azure AD tenant (i.e. single tenant)
> AzureADMultipleOrgs - Users with a Microsoft work or school account in any organization’s Azure AD tenant (i.e. multi-tenant)
> AzureADandPersonalMicrosoftAccount - Users with a personal Microsoft account, or a work or school account in any organization’s Azure AD tenant

I want to know if I can select AzureADMyOrg in the manifest for this repo.

**Comment by jasonjoh** [comment]
Yes you can. The instructions tell you to use that option so that devs using a personal account can still try out the sample :).
