### ISSUE TITLE
Real documentation for msgraph use is missing

### ISSUE THREAD

**Issue by Younnah** [microsoftgraph/msgraph-training-rubyrailsapp#22]
Hi! 👋

I don't know if this is the right place for my question, but I don't know where to ask it.

I have been working for several days on integrating Outlook into my application (mainly for calendars).
I can't find any documentation that could help me: in Microsoft documentation, a calendar has a `canEdit` property.
However, when I have a `MicrosoftGraph::Calendar` object, I can't find this property...

Here is my code:

```ruby
def calendars
   graph = get_microsoft_graph
      
   response = graph.me.calendars
   response.each do |c|
        
   end
end
```

Is it possible that someone helps me on this? Where can I find the code for the Calendar class for ruby?
Thank you for your help!

**Comment by jasonjoh** [comment]
This example doesn't use that gem, so this isn't the best place to ask :). You'll probably have better luck in the Ruby SDK's GitHub repository at https://github.com/microsoftgraph/msgraph-sdk-ruby (which should also have the code for that class).

**Comment by Younnah** [comment]
Thank you !
