### ISSUE TITLE
Azure Active Directory app registration bugs

### ISSUE THREAD

**Issue by Younnah** [microsoftgraph/msgraph-training-rubyrailsapp#25]
Hi everyone!

I have a bug in my azure active directory account.
I can register an application, but when I configure it I have some problems.

I can go on the "Personnalisation" or "authorized API", and there is the errors that I have :
<img width="1552" alt="Screenshot 2020-05-14 at 13 01 42" src="https://user-images.githubusercontent.com/26743683/81927007-36ef7900-95e3-11ea-8a17-aa2f7df60f63.png">

I have a simple account without any subscriptions. Can anyone help me? I can't access to all application settings. I search in the web but I did not find a similar problem.

Thank you, and good day!

**Comment by jasonjoh** [comment]
Sorry, I have no idea. You can get support via the `?` menu in the portal though.
