### ISSUE TITLE
Remote Logout Flow

### ISSUE THREAD

**Issue by khani3s** [microsoftgraph/msgraph-training-rubyrailsapp#26]
I am trying to implement the remote logout flow over this example. 
I registered a logout url and I am receiving a request from microsoft. When I log out of office365 rails receives a request with sid and iss

How do I know which user logged out? 
I think that I should do this using sid but I didn't find this information during sso

**Comment by jasonjoh** [comment]
Can you provide more information (link to the flow you're referring to)? This is a little beyond the scope of this sample, but if it's something I can quickly answer I'm happy to help.

**Comment by khani3s** [comment]
I am trying to implement the following flow:

https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-openid-connect-code#single-sign-out

I filled the LogoutUrl on this screen: https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Authentication/appId/737269e8-e69a-4507-b95c-052aa04a193e/isMSAApp/

and implemented a endpoint. But I couldn't find a way to relate the data received to the user's session

**Comment by jasonjoh** [comment]
I see. I just tried this here and I see that it passes just the one parameter as a query parameter: `sid=xxxx`. Their docs don't provide much information on that parameter. Let me ask internally and see what I can find out.

**Comment by khani3s** [comment]
Thank you very much! I've been trying to figure out how to correlate this information all week.

**Comment by jasonjoh** [comment]
Ok, so the `sid` value is the session ID. What you're supposed to do is [configure your app registration to add this claim to your ID tokens](https://docs.microsoft.com/azure/active-directory/develop/active-directory-optional-claims), then save that value with your user info. The sample as it is pretty much ignores the ID token so you'd have to extend the auth provider to dig that information out.

If you need more info on this, I'd recommend posting feedback with the feedback control on https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#single-sign-out.
