### ISSUE TITLE
webpacker:install requires yarn

### ISSUE THREAD

**Issue by martonnagy** [microsoftgraph/msgraph-training-rubyrailsapp#27]
Hi Guys,

Great tutorial!
However, when you follow the tutorial and trying to start the server for the first time you get a huge stack trace dump because yarn is not installed. It is actually saying in the stack dump, but it can be quite intimidating for the uninitiated. 😎 
I would add it to step 1 after the line "In this exercise, you will use Ruby on Rails to build a web app."

Cheers,
Marton

**Comment by jasonjoh** [comment]
Thanks @martonnagy for reporting. I did not encounter this issue, but maybe I already had yarn, or the Windows installer includes it. I'll investigate this for the next refresh of the tutorial.

**Comment by martonnagy** [comment]
Thanks @jasonjoh

**Comment by jasonjoh** [comment]
According to [their docs](https://guides.rubyonrails.org/getting_started.html#creating-a-new-rails-project-installing-rails), Yarn is a pre-req.

> Before you install Rails, you should check to make sure that your system has the proper prerequisites installed. These include:
>
> - Ruby
> - SQLite3
> - Node.js
> - Yarn
