### ISSUE TITLE
Application Secret input form is not displayed in Microsoft Graph Quick Start of the ja-JP version.

### ISSUE THREAD

**Issue by jinroq** [microsoftgraph/msgraph-training-rubyrailsapp#28]
Application Secret input form is not displayed in the ja-JP version of Microsoft Graph Quick Start. So running `bundle exec rails server` command on the ja-JP version causes "OAuth2::Error (invalid_client: AADSTS7000215: Invalid client secret is provided."

<img width="1577" alt="quick_start_en-us" src="https://user-images.githubusercontent.com/2787780/98124002-f6b7e600-1ef5-11eb-81ed-38f0e6fdc06a.png">

<img width="1578" alt="quick_start_ja-JP" src="https://user-images.githubusercontent.com/2787780/98124016-f91a4000-1ef5-11eb-8a3c-80a7c3989fe7.png">

**Comment by jasonjoh** [comment]
I've reported this to the engineering team that maintains the quick start download tool. Closing this as out of scope for this repository.
