### ISSUE TITLE
upgrade omniauth-rails_csrf_protection gem to 1.0

### ISSUE THREAD

**Issue by lauer** [microsoftgraph/msgraph-training-rubyrailsapp#37]
The tutorial failed in my setup with a Omniauth auth error.

`omniauth: Attack prevented by OmniAuth::AuthenticityTokenProtection`

I upgraded the gemfile to 
`gem 'omniauth-rails_csrf_protection', '~> 1.0.0'`

And ran `bundle install`

And then it worked again. 

https://github.com/microsoftgraph/msgraph-training-rubyrailsapp/blob/5a35116c5aed22f70288f3e6e97e205fe2873341/demo/graph-tutorial/Gemfile#L56

**Comment by jasonjoh** [comment]
Thanks for reporting.

**Comment by jasonjoh** [comment]
Fixed in #38
